Repository ponylang/peg, pull requests merged in 2022-02, with the labels that each got.

#25 Add nodoc annotation to test code
  peg/_test.pony
Labels: discuss during sync

#26 Update to work with object capabilities changes in Pony 0.49.0
  .github/workflows/pr.yml
  .release-notes/obj-cap-change.md
  examples/compiler/main.pony
  peg/_test.pony
Labels: changelog - changed, do not merge, discuss during sync

#27 Update to address PonyTest package being renamed
  .github/workflows/pr.yml
  .release-notes/ponytest.md
  peg/_test.pony
Labels: changelog - fixed, discuss during sync

#28 Run PRs against release builds again
  .github/workflows/pr.yml
Labels: discuss during sync
